// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9H04u8YtaQ-SOETOK6KQnkdW_SL1v9ZU',
    appId: '1:227014850222:web:a2cda20028642e561b1f3f',
    messagingSenderId: '227014850222',
    projectId: 'firstapp-4aac3',
    authDomain: 'firstapp-4aac3.firebaseapp.com',
    storageBucket: 'firstapp-4aac3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5Gp_bYthJGiHpVrjDuCFQln4TPPbwz0',
    appId: '1:227014850222:android:e065cbc46c51bdb31b1f3f',
    messagingSenderId: '227014850222',
    projectId: 'firstapp-4aac3',
    storageBucket: 'firstapp-4aac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsVDRdtpAc8zZxuahltO547f3GicSQ12w',
    appId: '1:227014850222:ios:4880bcde43f36c011b1f3f',
    messagingSenderId: '227014850222',
    projectId: 'firstapp-4aac3',
    storageBucket: 'firstapp-4aac3.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsVDRdtpAc8zZxuahltO547f3GicSQ12w',
    appId: '1:227014850222:ios:fab81cff72516d9a1b1f3f',
    messagingSenderId: '227014850222',
    projectId: 'firstapp-4aac3',
    storageBucket: 'firstapp-4aac3.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
